### ISSUE TITLE
how to eat this receipt effectively?

### ISSUE THREAD

**Issue by randomwangran** [sjlleo/pudong-bus-operation-diagram#1]
The manual is too easy to install. Thus, imposing significant effort for a normal people to play with it.

Can you provide a Makefile or something similar to the Makefile concept?

**Comment by sjlleo** [comment]
Thank you for your suggestion ;) I've rewritten it.

**Comment by randomwangran** [comment]
thanks for contribution. I will test it shortly and report it back shortly.
