### ISSUE TITLE
website cannot find the route

### ISSUE THREAD

**Issue by randomwangran** [sjlleo/pudong-bus-operation-diagram#3]
![image](https://user-images.githubusercontent.com/8197831/74358513-8bd6e580-4d8f-11ea-9f18-6b498c6df180.png)

Anything wrong with my search keywords or?

**Comment by sjlleo** [comment]
You need to type in the line name like `71` ,`795路`

![image](https://user-images.githubusercontent.com/13616352/74397061-cbb0d200-4e4e-11ea-8379-12ded72c1070.png)

![image](https://user-images.githubusercontent.com/13616352/74397263-33671d00-4e4f-11ea-9eeb-9e158b03c420.png)

![image](https://user-images.githubusercontent.com/13616352/74397318-5396dc00-4e4f-11ea-8fa7-67ce1b1dab38.png)

**Comment by randomwangran** [comment]
![image](https://user-images.githubusercontent.com/8197831/74397863-ac308f80-4de3-11ea-9d3a-5d48b512dad8.png)

Thanks, it is really cool.
